**Ejercicio 1:** Selecciona una API pública y extrae datos utilizando Python.

Tengo como afición la astronomía y me ha parecido realizar este ejercicio con algo relacionado al tema.

Selecciono la API de la NASA, del Servicio de Detección de objetos Cercanos a la Tierra (NeoWs) que se encuentra dentro de la página https://api.nasa.gov/ para ver si puedo obtener algunos datos relacionados con objetos entre los días 17 y 18 de octubre de 2024.

In [16]:
import requests
import pandas as pd

# Hago la solicitud a  la API de la NASA 

URL = "https://api.nasa.gov/neo/rest/v1/feed?start_date=2024-10-17&end_date=2024-10-18&api_key=DEMO_KEY"
response = requests.get(URL)

if response.status_code == 200:
    data = response.json()
    print("Solicitud Exitosa")
    
else:
    print("Error en la solicitud, detalles:", response.text)

Solicitud Exitosa

Quiero saber como están estructurados los datos del objeto creado y los inspecciono mediante la función "keys"

In [22]:
data.keys()

dict_keys(['links', 'element_count', 'near_earth_objects'])

Dentro del campo near_earth_objects creo que es donde puedo encontrar los datos importantes, consulto la estructura para poder elegir los datos que me interesan para crear un dataframe con ellos.

In [25]:
# Comento la línea de código porque en github me muestra el resultado completo de una lista de 40 objetos y es una salida muy larga, a efectos en VSC me indicó la información
# que necesitaba al limitarla.

# data['near_earth_objects'] (código utilizado)

Creo la estructura para el dataframe con los datos de las columnas en español para que sean comprensibles y con los elementos que me interesan

In [19]:
# Extraigo el diccionario del objeto data que contiene la información de las fechas indicadas en la petición a la API, el diccionario de tal manera que las claves son las fechas y los valores son listas de asteriodes que se acercarán en esas fechas

near_earth_objects = data['near_earth_objects']

# inicializo una lista vacía donde se almacenarán los datos en formato diccionario, para posteriormente crear el dataframe

all_neo_data = []

# Se realiza un bucle sobre las fechas, se itera sobre cada clave o fecha y se hace un bucle sobre los asteriodes
for date in near_earth_objects:
    for neo in near_earth_objects[date]:
        neo_data = {
            'id': neo['id'],
            'nombre': neo['name'],
            'magnitud_absoluta_h': neo['absolute_magnitude_h'],
            'diametro_min_estimado_km': neo['estimated_diameter']['kilometers']['estimated_diameter_min'],
            'diametro_max_estimado_km': neo['estimated_diameter']['kilometers']['estimated_diameter_max'],
            'potencialmente_peligroso': neo['is_potentially_hazardous_asteroid'],
            'fecha_aproximacion_cercana': neo['close_approach_data'][0]['close_approach_date'],
            'velocidad_relativa_km_per_seg': neo['close_approach_data'][0]['relative_velocity']['kilometers_per_second'],
            'distancia_fallo_km': neo['close_approach_data'][0]['miss_distance']['kilometers'],
            'cuerpo_que_orbita': neo['close_approach_data'][0]['orbiting_body']
        }
        all_neo_data.append(neo_data) # Se crea el diccionario (neo_data) donde se almacena la información de cada asteroide en el diccionario vacío (all_neo_data)

# Convierto los datos en un Dataframe e imprimo el resultado

df_neo = pd.DataFrame(all_neo_data)

# Muestro el resultado

df_neo

,id,nombre,magnitud_absoluta_h,diametro_min_estimado_km,diametro_max_estimado_km,potencialmente_peligroso,fecha_aproximacion_cercana,velocidad_relativa_km_per_seg,distancia_fallo_km,cuerpo_que_orbita
0,2483547,483547 (2003 WM25),17.650,0.784431,1.754042,False,2024-10-18,9.3986954613,36254254.770454259,Earth
1,3137843,(2002 RD27),18.140,0.625972,1.399716,False,2024-10-18,12.6975359942,69734228.456075999,Earth
2,3145497,(2002 YO2),22.700,0.076658,0.171412,False,2024-10-18,4.4510357534,69033272.631524638,Earth
3,3529626,(2010 MA),25.700,0.019256,0.043057,False,2024-10-18,8.5877838298,46135839.613723096,Earth
4,3761647,(2016 UY35),24.700,0.030518,0.068240,False,2024-10-18,18.0779724934,58180815.51882084,Earth
5,54016334,(2020 FV3),27.700,0.007666,0.017141,False,2024-10-18,17.4745586299,59113575.382186742,Earth
6,54051583,(2020 QP6),20.730,0.189913,0.424659,False,2024-10-18,9.115305361,31590050.163075345,Earth
7,54055117,(2020 TN3),24.200,0.038420,0.085909,False,2024-10-18,18.9916021102,27921083.802604447,Earth
8,54316690,(2022 UO),26.530,0.013139,0.029379,False,2024-10-18,16.29423043,45863697.616287293,Earth
9,54320707,(2022 UO10),26.760,0.011818,0.026427,False,2024-10-18,10.3025532627,7816690.200871103,Earth
10,54347994,(2023 EN2),23.120,0.063176,0.141267,False,2024-10-18,23.4907483903,69169584.864287808,Earth
11,54445848,(2024 LE1),26.310,0.014540,0.032512,False,2024-10-18,7.7794602138,49584342.351512673,Earth
12,54482434,(2024 RV50),20.970,0.170042,0.380224,True,2024-10-18,15.5740330005,7417329.411838163,Earth
13,54487286,(2024 TX2),23.820,0.045767,0.102339,False,2024-10-18,13.5391459573,11416441.217241881,Earth
14,54487954,(2024 TN4),22.570,0.081387,0.181987,False,2024-10-18,11.860549732,42334375.437058714,Earth
15,54489676,(2024 TX8),24.230,0.037893,0.084731,False,2024-10-18,12.4967201863,14099693.927991923,Earth
16,54490132,(2024 TT9),24.200,0.038420,0.085909,False,2024-10-18,14.7304381847,9752846.990020359,Earth
17,54494098,(2024 TB22),19.323,0.363040,0.811783,True,2024-10-18,22.0048475276,11433124.266985772,Earth
18,2462238,462238 (2008 CN1),20.660,0.196135,0.438571,True,2024-10-17,15.3649328146,68174282.335175053,Earth
19,3388311,(2007 TQ24),22.060,0.102933,0.230165,False,2024-10-17,12.2165910106,35567947.599252872,Earth
20,3775093,(2017 KR31),24.100,0.040230,0.089958,False,2024-10-17,14.067359043,56970564.501941332,Earth
21,3836113,(2018 VW4),24.520,0.033155,0.074138,False,2024-10-17,23.7531336241,65128846.942923832,Earth
22,3879238,(2019 UZ),27.800,0.007321,0.016370,False,2024-10-17,17.2745006981,36606099.670666532,Earth
23,3883101,(2019 UZ7),21.040,0.164647,0.368163,False,2024-10-17,21.8717027588,63134021.609107326,Earth
24,3892267,(2019 UH14),23.800,0.046191,0.103286,False,2024-10-17,10.3320999537,3044662.659413523,Earth
25,3989721,(2020 CU1),24.190,0.038597,0.086306,False,2024-10-17,8.2046893125,14249861.960353854,Earth
26,54144232,(2021 JN2),23.770,0.046833,0.104722,False,2024-10-17,20.2193965004,55254431.861810698,Earth
27,54145782,(2021 JG9),25.200,0.024241,0.054205,False,2024-10-17,14.3161184392,65749986.649030707,Earth
28,54205435,(2021 TN6),25.060,0.025856,0.057815,False,2024-10-17,9.9869841071,67554784.525530576,Earth
29,54243523,(2022 BM5),25.630,0.019886,0.044467,False,2024-10-17,7.3368166987,48731550.328751011,Earth
30,54393421,(2023 TK12),25.770,0.018645,0.041691,False,2024-10-17,18.9889273099,31789054.375219415,Earth
31,54395029,(2023 UH),26.130,0.015796,0.035322,False,2024-10-17,11.8015350248,53015617.054517949,Earth
32,54467171,(2024 NN11),19.310,0.365220,0.816658,False,2024-10-17,7.8808285914,61689125.241068367,Earth
33,54482419,(2024 SD2),25.650,0.019704,0.044060,False,2024-10-17,6.0977852005,3869210.484640889,Earth
34,54483132,(2024 ST2),25.140,0.024920,0.055724,False,2024-10-17,4.7190369218,13464372.493406918,Earth
35,54483152,(2024 SP3),21.840,0.113908,0.254706,False,2024-10-17,4.0814310006,47146714.054400317,Earth
36,54487060,(2024 TO1),25.620,0.019978,0.044672,False,2024-10-17,6.5609162288,8458811.591677171,Earth
37,54490139,(2024 TC10),21.550,0.130183,0.291099,False,2024-10-17,18.9817398741,51624036.604397853,Earth
38,54490522,(2024 TQ11),23.141,0.062568,0.139907,False,2024-10-17,13.6013985235,27585928.788758724,Earth
39,54491553,(2024 TC15),26.862,0.011276,0.025214,False,2024-10-17,9.2205371483,1835002.284844349,Earth

Quiero saber de toda esta lista cuales son los potencialmente peligrosos

In [10]:

cantidad_peligrosos = df_neo['potencialmente_peligroso'].sum()

print(f'Cantidad de objetos potencialmente peligrosos: {cantidad_peligrosos}')

Cantidad de objetos potencialmente peligrosos: 3

Quiero saber cuáles son estos objetos

In [20]:
objetos_peligrosos = df_neo['potencialmente_peligroso'] == True

df_neo[objetos_peligrosos]

,id,nombre,magnitud_absoluta_h,diametro_min_estimado_km,diametro_max_estimado_km,potencialmente_peligroso,fecha_aproximacion_cercana,velocidad_relativa_km_per_seg,distancia_fallo_km,cuerpo_que_orbita
12,54482434,(2024 RV50),20.970,0.170042,0.380224,True,2024-10-18,15.5740330005,7417329.411838163,Earth
17,54494098,(2024 TB22),19.323,0.363040,0.811783,True,2024-10-18,22.0048475276,11433124.266985772,Earth
18,2462238,462238 (2008 CN1),20.660,0.196135,0.438571,True,2024-10-17,15.3649328146,68174282.335175053,Earth

Con la información de esta consulta destaco por ejemplo el objeto ***2024 TB22*** (índice 17) se considera potencialmente peligroso, explico los valores obtenidos de este objeto:

- **Magnitud absoluta:** 19.32 (la brillo del objeto, cuando menor el número más brillantes y por lo tanto más grande, ejemplo: el planeta Venus tiene una magnitud de -4,38, una estrella como Polaris, la estrella polar es de +1.97 )

- **Diámetro estimado:** entre 363 y 812 mts. De impactar en la tierra podría causar un daño regional significativo.

- **Potencialmente peligroso:** True, la NASA lo considera potencialmente peligroso.

- **Fecha de aproximación cercana:** 18 de octubre de 2024

- **Velocidad relativa:** 22 km/s velocidad extremadamente alta en relación con la tierra, en caso de impacto la energía sería considerable.

- **Distancia de fallo:** 11 millones de km. aunque esté clasificado como potencialmente peligroso, pasará a una distancia segura (más lejos que la distancia entre la tierra y la luna)

- **Trayectoria:** tiene una trayectoria que lo llevará cerca de la tierra.